# -----------------------------------------
# docker-compose.yml
# -----------------------------------------

services:
  web:
    build: .
    container_name: novas-blog-dev
    ports:
      - "4321:4321"
    environment:
      - HOST=0.0.0.0
    volumes:
      - .:/usr/src/app
      # node_modulesはマウント対象から除外（コンテナ内のものを使用するため）
      - /usr/src/app/node_modules