# -----------------------------------------
# docker-compose.yml
# -----------------------------------------

services:
  # サービス名（任意）
  web:
    # 現在のディレクトリにあるDockerfileを使用してイメージをビルド
    build: .
    # コンテナ名（任意）
    container_name: my-portfolio-bun
    # ポートのマッピング
    # [ホストPCのポート]:[コンテナのポート]
    ports:
      - "4321:4321"
    # ボリュームのマウント
    # [ホストPCのパス]:[コンテナのパス]
    volumes:
      - .:/usr/src/app
      # node_modulesはマウント対象から除外（コンテナ内のものを使用するため）
      - /usr/src/app/node_modules